### ISSUE TITLE
Sobre el gobierno participativo

### ISSUE THREAD

**Issue by davidhdz** [accesolibre/gobiernoabierto#1]
Me parece que la introducción del tercer párrafo, donde se habla del gobierno participativo en Venezuela 

> El concepto de gobierno abierto es, pues, profundamente compatible con la noción de gobierno participativo contenida en la Constitución de 1999, pero la lleva un paso más allá: en lugar de limitarse a establecer mecanismos electorales para la participación ciudadana,[...]

queda bastante corta pues el espíritu de participación y protagonismo plasmado en la Constitución van más allá de limitarse a lo electoral, como ejemplo coloco a continuación los artículos 62 y 70.

> **Artículo 62**. Todos los ciudadanos y ciudadanas tienen el derecho de participar libremente en los asuntos públicos, directamente o por medio de sus representantes elegidos o elegidas.
> 
> La participación del pueblo en la formación, ejecución y control de la gestión pública es el medio necesario para lograr el protagonismo que garantice su completo desarrollo, tanto individual como colectivo. Es obligación del Estado y deber de la sociedad facilitar la generación de las condiciones más favorables para su práctica.
> 
> **Artículo 70**. Son medios de participación y protagonismo del pueblo en ejercicio de su soberanía, en lo político: la elección de cargos públicos, el referendo, la consulta popular, la revocatoria del mandato, las iniciativas legislativa, constitucional y constituyente, el cabildo abierto y la asamblea de ciudadanos y ciudadanas cuyas decisiones serán de carácter vinculante, entre otros; y en lo social y económico, las instancias de atención ciudadana, la autogestión, la cogestión, las cooperativas en todas sus formas incluyendo las de carácter financiero, las cajas de ahorro, la empresa comunitaria y demás formas asociativas guiadas por los valores de la mutua cooperación y la solidaridad.
> 
> La ley establecerá las condiciones para el efectivo funcionamiento de los medios de participación previstos en este artículo

Mi sugerencia es imprimirle el verdadero valor de gobierno participativo con el que contamos y que practicamos en el país, o al menos el que se refleja en la Constitución.

**Comment by ghostbar** [comment]
+1 ¿Cómo?

**Comment by davidhdz** [comment]
Quizá lo siguiente ayude, una solución sería eliminar el texto que le imprime el carácter limitante al concepto dado en la Constitución: "_pero la lleva un paso más allá: en lugar de limitarse a establecer mecanismos electorales para la participación ciudadana,_". 

El párrafo quedaría de la siguiente forma:

> El concepto de gobierno abierto es, pues, profundamente compatible con la noción de gobierno participativo contenida en la Constitución de 1999. La idea del gobierno abierto parte del concepto de innovación para crear mejoras en la eficiencia, la eficacia y la calidad de los sistemas y procesos gubernamentales: el gobierno se convierte así en una plataforma para la creación de innovación social, proporcionando recursos, estableciendo reglas, pero permitiendo a los ciudadanos, como individuos o de manera organizada, llevar a cabo acciones verdaderamente significativas para el cambio.
